version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
